/*************************************** CUSTOMER SEARCH ACTIONS ***************************************/

export const CUSTOMERS_DETAILS_VISIBILITY_SET = 'CUSTOMERS_DETAILS_VISIBILITY_SET';
export const CUSTOMERS_DETAILS_FETCH = 'CUSTOMERS_DETAILS_FETCH';
export const CUSTOMERS_DETAILS_IS_FETCHING = 'CUSTOMERS_DETAILS_IS_FETCHING';
export const CUSTOMERS_DETAILS_IS_LOADED = 'CUSTOMERS_DETAILS_IS_LOADED';
export const CUSTOMERS_DETAILS_IS_ERROR = 'CUSTOMERS_DETAILS_IS_ERROR';
export const CUSTOMER_SELECT = 'CUSTOMER_SELECT';
export const CUSTOMER_SEARCH_FILTER_CHANGE = 'CUSTOMER_SEARCH_FILTER_CHANGE'; 
export const CUSTOMER_SEARCH_VALUE_CHANGE = 'CUSTOMER_SEARCH_VALUE_CHANGE';
